#!/bin/sh

# 2022 eCTF
# Example Generate secrets
# Jake Grycel
#
# (c) 2022 The MITRE Corporation
#
# This source file is part of an example system for MITRE's 2022 Embedded System
# CTF (eCTF). This code is being provided only for educational purposes for the
# 2022 MITRE eCTF competition, and may not meet MITRE standards for quality.
# Use this code at your own risk!

openssl genrsa -out /secrets/private-key.pem 2048
openssl rsa -in /secrets/private-key.pem -pubout -out /secrets/public-key.pem
